server:
  port: 8765
spring:
  application:
    name: edge-server

eureka:
  instance:
    secure-port-enabled: false
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761}/eureka/

zuul:
  routes:
    hello-service:
      path: /hello/**
      stripPrefix: false

