spring:
  application:
    name: hello-service
server:
  port: ${PORT:8080}
  context-path: /hello
eureka:
  instance:
    nonSecurePort: ${server.port:8080}
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761}/eureka/
