spring:
  application:
    name: counter-service
server:
  port: ${PORT:8081}
eureka:
  instance:
    nonSecurePort: ${server.port:9304}
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761}/eureka/
